M0-CraftBlocker:
  NoPermission: '&4You do not have permission for this command'
  ConfigReloaded: '&2Config has been reloaded'
  CraftBlocked: '&4You cannot craft this item.'
  BlockedItems:
    - 'HOPPER'