name: M0-CraftBlocker
main: me.M0dii.CraftBlocker.Main
description: M0-CraftBlocker
version: 1.2
api-version: 1.16
author: M0dii
permissions:
  m0craftblocker.bypass:
    description: Bypass the restriction.
    default: op